sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.token=sqp_10bfd777322e792bad0d730dabb7ef21a178d829
sonar.projectKey=mohamed-amine-cicd-frontend-project
sonar.projectName=Mohamed-Amine - TaskList Frontend

sonar.sources=src
sonar.tests=src/__tests__

sonar.exclusions=**/node_modules/**,src/main.tsx,src/vite-env.d.ts
sonar.test.exclusions=src/__tests__/**

sonar.coverage.exclusions=src/main.tsx,src/App.tsx,src/vite-env.d.ts,src/t      

sonar.javascript.lcov.reportPaths=coverage/lcov.info