sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr
sonar.token=sqp_40117b380490b2418413518a1b2e6838339c0019
sonar.projectKey=mohamed-amine-cicd-frontend-project
sonar.projectName=Mohamed-Amine - TaskList Frontend

# Indique à SonarQube où chercher le code source (ici, tout le dossier courant)
sonar.sources=.
# Optionnel : exclure le dossier node_modules pour éviter d'analyser les dépendances
sonar.exclusions=**/node_modules/**